import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header
          style={{
            backgroundColor: "darkgray",
            padding: "1rem",
            textAlign: "center",
          }}
        >
          {/* <h4>Header</h4>
           */}
           <Navbar />
        </header>
        <section></section>
        <div className="container" style={{width: "80%",
    margin: "50px auto;"}}>
        {children}
        </div>
        

        <footer
          style={{
            backgroundColor: "darkgray",
            padding: "1rem",
            textAlign: "center",
            marginTop: "10rem",
          }}
        >
          <h4>Footer</h4>
        </footer>
      </body>
    </html>
  );
}
